import { TypographyStylesProvider } from '@mantine/core';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

/**
 * Model output is markdown, and until this component existed it rendered as
 * literal asterisks and hashes — every draft, every verdict, every final answer.
 *
 * NO RAW HTML, deliberately. `rehype-raw` is not installed and must not be: the
 * text here is generated by a third-party model from a prompt the user wrote,
 * which makes it the least trustworthy string in the product. react-markdown
 * escapes HTML by default, so a model that emits a `<script>` renders it as the
 * characters it is. GFM is on because tables and strikethrough are ordinary in
 * model answers and neither is in CommonMark.
 *
 * `TypographyStylesProvider` supplies the element styles — Mantine's own
 * headings, lists, code and blockquotes — so this file needs no CSS and no hex.
 */
export function Markdown({ children, size = 'sm' }) {
  if (!children) return null;

  return (
    <TypographyStylesProvider
      // The provider's defaults are sized for an article; a draft card is not
      // one. Everything inside inherits, so this is set once per block.
      style={{ fontSize: size === 'sm' ? '0.875rem' : '1rem', lineHeight: 1.6 }}
      className="quorum-markdown"
    >
      <ReactMarkdown
        remarkPlugins={[remarkGfm]}
        components={{
          // Any link a model produces goes to a site we know nothing about.
          a: ({ node, ...props }) => <a {...props} target="_blank" rel="noopener noreferrer nofollow" />,
        }}
      >
        {children}
      </ReactMarkdown>
    </TypographyStylesProvider>
  );
}
